<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LucideBlazor" Version="1.0.4"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.3"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.0" PrivateAssets="all"/>
        <PackageReference Include="Riok.Mapperly" Version="5.0.0-next.2"/>
        <PackageReference Include="ShadcnBlazor" Version="1.0.14"/>
        <PackageReference Include="ShadcnBlazor.Extras" Version="1.0.14"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\blazor.Shared\blazor.Shared.csproj"/>
    </ItemGroup>


</Project>
