services:
  blazor.api:
    image: blazor.api
    build:
      context: .
      dockerfile: blazor.Api/Dockerfile

  blazor.frontend:
    image: blazor.frontend
    build:
      context: .
      dockerfile: blazor.Frontend/blazor.Frontend/Dockerfile

  blazor.frontend.client:
    image: blazor.frontend.client
    build:
      context: .
      dockerfile: blazor.Frontend/blazor.Frontend.Client/Dockerfile

