name: Build CLI
on:
  workflow_dispatch:
  push:
    branches:
      - projectify

jobs:
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - run: cd cli && cargo install
      - run: cd cli && cargo build
      - uses: actions/upload-artifact@v4
        with:
          name:
          path: cli/target/debug/cli