name: Build CLI
on:
  workflow_dispatch:
  push:
    branches:
      - projectify

permissions:
  packages: write
  contents: write

jobs:
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - run: cd cli && cargo install --path .
      - run: cd cli && cargo build
      - uses: actions/upload-artifact@v4
        with:
          name: projectify
          path: /home/runner/work/Project-Templates/Project-Templates/cli/target/debug/cli
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.run_id }}
          title: Projectify build ${{ github.run_id }}
